# Generated by Django 4.1.2 on 2023-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_post_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='emissions',
            field=models.FloatField(default=0.0, help_text='Amount in kilograms of CO2 saved'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='energy',
            field=models.FloatField(default=0.0, help_text='Amount in watts of energy saved'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='plastic',
            field=models.FloatField(default=0.0, help_text='Amount in bottles of plastic saved'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='trees',
            field=models.FloatField(default=0.0, help_text='Number of trees planted'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='water',
            field=models.FloatField(default=0.0, help_text='Amount in litres of water saved'),
        ),
    ]
