# Generated by Django 4.1.2 on 2023-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_emissions_challenge_energy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='challenge',
            name='proof',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
