# Generated by Django 4.1.2 on 2023-04-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_rename_description_challenge_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(max_length=280),
        ),
    ]
