# Generated by Django 4.1.2 on 2023-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_post_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='word',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
